### ISSUE TITLE
Erno 2; No such file or directory

### ISSUE THREAD

**Issue by Niemand112233** [PetervanLunteren/AddaxAI#74]
Hi,

I updated to v6.0.2 and now I face this problem:

Step 1-3 went smoothly, but step 4 produce this error: 

"An error hass occured: Erno 2: No such file or direcotry" and then it gives me the path of the first file.

the first file has been copied to the output location, but the boxes were not drawn. 

The same happens when I rerun an old dataset which was successful post-processed before with v.6.0.1

**Comment by Niemand112233** [comment]
I tried installing v6.0.1 with the installer from github...but it installed v6.0.2??

**Comment by PetervanLunteren** [comment]
Hi @Niemand112233,

> Hi,
> 
> I updated to v6.0.2 and now I face this problem:
> 
> Step 1-3 went smoothly, but step 4 produce this error:
> 
> "An error hass occured: Erno 2: No such file or direcotry" and then it gives me the path of the first file.
> 
> the first file has been copied to the output location, but the boxes were not drawn.
> 
> The same happens when I rerun an old dataset which was successful post-processed before with v.6.0.1

Could you share a bug report with a minimal reproducible example with me? More info how to in the [AddaxAI FAQ](https://addaxdatascience.com/addaxai/#FAQ). 

> I tried installing v6.0.1 with the installer from github...but it installed v6.0.2??

Originally, it was indeed set up to install the specific version. However, that requires the versions to be separately stored in a cloud bucket, which costs money. Given the number donations coming in, I decided to host only the latest version to reduce monthly costs. Feel free to [donate](https://addaxdatascience.com/addaxai/#donate) and I can rebuild v6.01 for you again.

**Comment by Niemand112233** [comment]
Sure, this is the output: 

`C:\Users\User\AddaxAI_files>echo off
['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C:\\Users\\User\\AddaxAI_files\\AddaxAI', 'C:\\Users\\User\\AddaxAI_files\\cameratraps\\megadetector', 'C:\\Users\\User\\AddaxAI_files\\cameratraps', 'C:\\Users\\User\\AddaxAI_files', 'C:\\Users\\User\\AddaxAI_files\\AddaxAI', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\python38.zip', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\DLLs', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\lib', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\lib\\site-packages', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\lib\\site-packages\\win32', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\lib\\site-packages\\win32\\lib', 'C:\\Users\\User\\AddaxAI_files\\envs\\env-base\\lib\\site-packages\\Pythonwin']
EXECUTED : fetch_latest_model_info({})

Updated model_info.json successfully.
Checking release info
EXECUTED: model_cls_animal_options({'self': 'None'})

EXECUTED: toggle_cls_frame({})

model info updated in 1.02 seconds
Launch count: 1
EXECUTED: switch_mode({})

EXECUTED: switch_mode({})

EXECUTED: browse_dir({'var': <tkinter.StringVar object at 0x0000021658C1F0A0>, 'var_short': <tkinter.StringVar object at 0x0000021658C1F100>, 'dsp': <tkinter.Label object .!ctktoplevel.!ctkframe.!notebook.!frame.!canvas.!frame.!labelframe.!label2>, 'cut_off_length': 25, 'n_row': 0, 'n_column': 0, 'str_sticky': 'w', 'source_dir': True})

EXECUTED: browse_dir({'var': <tkinter.StringVar object at 0x0000021658C2A940>, 'var_short': <tkinter.StringVar object at 0x0000021658C2A9A0>, 'dsp': <tkinter.Label object .!ctktoplevel.!ctkframe.!notebook.!frame.!canvas.!frame.!labelframe4.!label2>, 'cut_off_length': 25, 'n_row': 0, 'n_column': 0, 'str_sticky': 'e', 'source_dir': False})

10000 46000000
EXECUTED: start_postprocess({})

EXECUTED: postprocess({'src_dir': 'X:/Rebhuhnprojekt_Detect/Kamera 1 umgehaengt (09.2024)/2025/02', 'dst_dir': 'X:/Rebhuhnprojekt_Detect/Detected/Detected Kamera 1 umgehaengt/2025/02', 'thresh': 0.7, 'sep': True, 'file_placement': 2, 'sep_conf': False, 'vis': True, 'crp': False, 'exp': True, 'plt': True, 'exp_format': 'XLSX', 'data_type': 'img'})

EXECUTED: move_files({'file': 'DCIM/100MEDIA/DSCF0001.JPG', 'detection_type': 'empty', 'var_file_placement': 2, 'max_detection_conf': 0.0, 'var_sep_conf': False, 'dst_root': 'X:/Rebhuhnprojekt_Detect/Detected/Detected Kamera 1 umgehaengt/2025/02', 'src_dir': 'X:/Rebhuhnprojekt_Detect/Kamera 1 umgehaengt (09.2024)/2025/02', 'manually_checked': False})

ERROR:
[Errno 2] No such file or directory: '\\\\192.168.50.22\\ssdnas\\Rebhuhnprojekt_Detect\\Kamera 1 umgehaengt (09.2024)\\2025\\02\\empty\\DCIM\\100MEDIA\\DSCF0001.JPG'

DETAILS:
Traceback (most recent call last):
  File "C:\Users\User\AddaxAI_files\AddaxAI\AddaxAI_GUI.py", line 948, in start_postprocess
    postprocess(src_dir, dst_dir, thresh, sep, file_placement, sep_conf, vis, crp, exp, plt, exp_format, data_type = "img")
  File "C:\Users\User\AddaxAI_files\AddaxAI\AddaxAI_GUI.py", line 550, in postprocess
    with Image.open(os.path.normpath(os.path.join(src_dir, file))) as pil_img:
  File "C:\Users\User\AddaxAI_files\envs\env-base\lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '\\\\192.168.50.22\\ssdnas\\Rebhuhnprojekt_Detect\\Kamera 1 umgehaengt (09.2024)\\2025\\02\\empty\\DCIM\\100MEDIA\\DSCF0001.JPG'`

The intersting thing is: "DSCF0001.JPG" is the only file which is successfully copied.

I can understand that the costs are too high to make every single version available. 

I hope to get some funding for some conservation project and if it is successful then I plan to donate some money because I plan to use your software quite often.

**Comment by PetervanLunteren** [comment]
I've found the bug. If you update / reinstall v6.02, it should be fixed. Can you confirm?

**Comment by Niemand112233** [comment]
Sorry for the late reply!

Yes, for images it works now. But for Videos I get this error: "cannot identify image file xxxx\\DSC01.MP4"

**Comment by PetervanLunteren** [comment]
Yes, that was a bug. Fixed in v6.04. Can you confirm?

**Comment by Niemand112233** [comment]
This error is gone now, but I am facing this one:

"UnboundLocalError: local variable 'height' referenced before assignment"

**Comment by PetervanLunteren** [comment]
I was not able to recreate the error, but I have a hunch of what is going on. I've adjusted the code in the latest release v6.05. Can you try to install that one and try again? https://addaxdatascience.com/addaxai-windows/

**Comment by Niemand112233** [comment]
I tried it but still the same error. The error message says the problem is in line 533 of the AddacAI_GUI.py. 

I tried to rerun a set of files which I successfully processed with version 6.0, but face the same error.

**Comment by Niemand112233** [comment]
I found the issue: 

The AddaxAI_GUI.py which was installed with the windows installer didn't have this part in it:

"# read shape again - this is a temporary solution
            # read in the hieght and width of the images and videos, as this was giving a bunch of bugs...
            if data_type == "img":
                img = cv2.imread(os.path.normpath(os.path.join(src_dir, file)))
                height, width = img.shape[:2]
            else:
                cap = cv2.VideoCapture(os.path.join(src_dir, file))
                width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                cap.release()"

I the file downloaded it directly from github and placed it into the installation folder and now it works. Funny thing is, AddaxAI tells me it is now v6.04 again after replacing the file. I think the updating of AddaxAI failed and caused the problem.

**Comment by PetervanLunteren** [comment]
That is very weird. Thanks for letting me know. I'll check if I can find something in the logs. 

Anyway, I can safely close this issue now. Good luck!
